### ISSUE TITLE
Twig powered templates possible?

### ISSUE THREAD

**Issue by ghost** [kerli81/kirby-securedpages#1]
Hello, I'm trying to incorporate your plugin with Twig powered templates. You use standard PHP. How can I override your template to use my Twig powered version? Thank you very much for your help!

Best regards
Mike

I'm running Kirby 3.2.5 on a PHP 7.3.10 local machine with the latest version of your plugin and the PHP dev server.

**Comment by marcus-at-localhost** [comment]
I'm using Blade templates and all I had to do was creating `site/templates/loginform.blade.php` and display the form. Should be similar to twig

**Comment by kerli81** [comment]
There is a workaround with custom login forms. So I expect there is no further enhancement needed. will close this issue
