### ISSUE TITLE
Multi language support?

### ISSUE THREAD

**Issue by ghost** [kerli81/kirby-securedpages#2]
Hello, 

does the plugin support multi-language setups? 

Once I add a second language and Kirby adds its langage path segment /de or /en after the domain, I get an error thrown because your function expects the first argument to be a Kirby page object or null, but a Kirby responder object is given, due to the redirect for the language.

`Argument 1 passed to Plugin\SecuredPage\RouterAfterHook::process() must be an instance of Kirby\Cms\Page or null, instance of Kirby\Cms\Responder given, called in /Users/mikewink/Sites/Kirby/secured/site/plugins/securedpages/index.php on line 29`

Current fix:

`if($result instanceof Responder) {
                    $result = null;
                }`

Once I check for the responder and return null like you optionally expect too, I get rid of the error.

I really like the plugin and would like to help to make it fit for multi-language scenarios too. :)

Best regards
Mike

I'm running Kirby 3.2.5 on a PHP 7.3.10 local machine with the latest version of your plugin and the PHP dev server.

**Comment by demlak** [comment]
could you please advise where to put this line?

**Comment by kerli81** [comment]
Fixed the problem! Will be in the next release!
