### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Kirby' not found

### ISSUE THREAD

**Issue by matthiasott** [kerli81/kirby-securedpages#4]
When I install kirby-securedpages via Composer, I get an error:

**Fatal error:** Uncaught Error: Class 'Kirby' not found in […]/mzur/kirby-uniform/config.php:3

Installing only kirby-uniform works fine. I also already tried a fresh `composer install`. 
My Kirby version is 3.3.6.

Any help is much apprechiated. 🤗

**Comment by kerli81** [comment]
I cannot reproduce it. Will close the issue. If it is still there, please let me know!
