### ISSUE TITLE
filterby.. search results

### ISSUE THREAD

**Issue by demlak** [kerli81/kirby-securedpages#8]
Hey.. is it possible to filter search results by user-role that is allowed to view a page?

for example securedpages-plugin disallows to view a specific subpage.. this subpage should not be shown in search results..

`$results = $site->index()->listed()->search($query, 'title|text');` <-- is there any user-filter-solution based on your plugin?

thx

**Comment by kerli81** [comment]
I played a little bit with some filters etc. and I came to following solution.

With this query you will be able to filter a collection of pages based on the permissions of the current user.
$results = $site->index()->listed()->filterBy('kerli81-securedpages', 'OnlyUserVisiblePages');

Will do hopefully a release in the next few days and this enhancement will be included. Please let me know if it works or if I should do further improvements.

**Comment by kerli81** [comment]
Version 1.2.0 will contain this enhancement. Will close this issue!
