### ISSUE TITLE
Error while using retour (kirby plugin)

### ISSUE THREAD

**Issue by demlak** [kerli81/kirby-securedpages#9]
Hey there..
just want to inform you:

https://github.com/distantnative/retour-for-kirby/issues/213#issuecomment-713493766

regards

**Comment by demlak** [comment]
~~as far as i can see, the problem seems to be solved by latest commits.~~

still problem

**Comment by distantnative** [comment]
As far as I can see, this plugin is making the false assumption that result here
https://github.com/kerli81/kirby-securedpages/blob/070feb07a6012bb3f34925c2fbb80b18c461d1e6/index.php#L25
would be either a Page or User object:
https://github.com/kerli81/kirby-securedpages/blob/070feb07a6012bb3f34925c2fbb80b18c461d1e6/src/RouterAfterHook.php#L10

However, it could also be a `Kirby\Cms\Response` (if not also others).

**Comment by kerli81** [comment]
should be fixed in the next release

**Comment by kerli81** [comment]
Version 1.2.0 will fix the problem. Will close this issue!
